spring.application.name=TnT-Dropbox

spring.datasource.url=jdbc:postgresql://localhost:5432/tnt_dropbox_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret-key=3a1022c47603b2b3d39fcd4c69863936564f3433c64c94165a4acbece5ddaca5
security.jwt.expiration-time=3600000
