spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/tnt_dropbox_db
spring.datasource.username=postgres
spring.datasource.password=postgres
security.jwt.secret-key=3a1022c47603b2b3d39fcd4c69863936564f3433c64c94165a4acbece5ddaca5
security.jwt.expiration-time=3600000
spring.jpa.hibernate.ddl-auto=none